---
# tasks file for ansible-nodejs

- include: nodejs_install.yml
  when: ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial'
  tags: [installation]

- include: nodejs_rollback.yml
  when: ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial'
  tags: [rollback]

- include: nodejs_testing.yml
  when: ansible_distribution_release == 'trusty' or ansible_distribution_release == 'xenial'
  tags: [testing]
